---
- name: add or remove host from domain
  hosts: win2.example.com
  tasks:
    - name: add or remove
      microsoft.ad.membership:
        dns_domain_name: EXAMPLE.COM
        workgroup_name: EXAMPLE
        state: '{{ domain_join }}'
        domain_admin_user: '{{ domain_admin_username }}'
        domain_admin_password: '{{ domain_admin_password }}'
      register: domainresult

    - name: reboot if needed
      ansible.windows.win_reboot:
      when: domainresult.reboot_required
  
    

