---
- name: registry update
  hosts: Windows
  force_handlers: true
  tasks:
    - name: update both values
      ansible.windows.win_regedit:
        path: '{{ item.keyPath }}'
        name: '{{ item.valueName }}'
        data: '{{ item.valueData }}'
        type: '{{ item.valueType }}'
      loop: '{{ registry_values_to_set }}'
      when: not item.performanceAffecting
      notify: reboot the server

    - name: pull a registry value
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\7-zip
        name: Path64
      register: statresult
      when:
        - ansible_facts.os_name == "Microsoft Windows Server 2019 Datacenter"
        - ansible_facts.memtotal_mb > 1024
        - '"Server 2019" in ansible_facts.os_name'
      notify: reboot the server

    - name: show that value
      ansible.builtin.debug:
        var: statresult.value
      when: >
        "Server 2019" in ansible_facts.os_name
        or "Server 2022" in ansible_facts.os_name

  handlers:
    - name: reboot the server
      ansible.windows.win_reboot:

  post_tasks:
    - name: run at the end
      ansible.windows.win_ping: