---
- name: registry update
  hosts: Windows
  tasks:
    - name: update the first value
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint
        name: NoWarningNoElevationOnInstall
        data: 0
        type: dword

    - name: update the second value
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint
        name: UpdatePromptSettings
        data: 0
        type: dword

    - name: pull a registry value
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\7-zip
        name: Path64
      register: statresult

    - name: show that value
      ansible.builtin.debug:
        var: statresult.value
