---
- name: registry update
  hosts: Windows
  tasks:
    - name: update both values
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint
        name: '{{ item }}'
        data: 0
        type: dword
      loop:
        - NoWarningNoElevationOnInstall
        - UpdatePromptSettings
        - AnotherMadeUpValue
        - FourthFakeValue
      register: loopresult

    - name: pull a registry value
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\7-zip
        name: Path64
      register: statresult

    - name: show that value
      ansible.builtin.debug:
        var: statresult.value
