---
- name: Play to show variables
  hosts: Windows
  gather_facts: false
  tasks:
    - name: Show web content variables
      ansible.builtin.debug:
        var: web_content

- name: Play to install IIS
  hosts: webservers
  max_fail_percentage: 50
  roles:
    - web

- name: Play to test
  hosts: database
  tasks:
    - name: Test connectivity
      ansible.windows.win_uri:
        url: http://win1.example.com
        return_content: true
      register: uriresult

    - name: put that content in c:\windows\temp
      ansible.windows.win_copy:
        content: '{{ uriresult["content"] }}'
        dest: c:\windows\temp\result.txt
    

- name: Test from the control node
  hosts: localhost
  tasks:
    - name: Test from this linux container
      ansible.builtin.uri:
        url: http://win1.example.com
