---
- name: Play to install IIS
  hosts: webservers
  tasks:
    - name: Install IIS feature
      ansible.windows.win_feature:
        name: >
          Web-Server
        state: present

    - name: Start the IIS service
      ansible.windows.win_service:
        name: "W3Svc"
        state: 'started'
        start_mode: auto

    - name: Copy out content
      ansible.windows.win_copy:
        content: |
          'Hell'o World
          From Tex"as
          Whe're it is still "too warm
        dest: c:\inetpub\wwwroot\index.html