---
- name: Play to show variables
  hosts: Windows
  gather_facts: false
  tasks:
    - name: Show web content variables
      ansible.builtin.debug:
        var: web_content

- name: Play to install IIS
  hosts: webservers
  vars:
    web_service: W3Svc
    web_feature: Web-Server
    web_index: index.html
  tasks:
    - name: Install IIS feature
      ansible.windows.win_feature:
        name: >
          {{ web_feature }}
        state: present

    - name: Start the IIS service
      ansible.windows.win_service:
        name: "{{ web_service }}"
        state: 'started'
        start_mode: auto

    - name: Copy out content
      ansible.windows.win_copy:
        content: '{{ web_content }}'
        dest: c:\inetpub\wwwroot\{{ web_index }}

- name: Play to test
  tasks:
    - name: Test connectivity
      ansible.windows.win_uri:
        url: http://win1.example.com
  hosts: database

- name: Test from the control node
  hosts: localhost
  tasks:
    - name: Test from this linux container
      ansible.builtin.uri:
        url: http://win1.example.com
