---
- name: Play to show variables
  hosts: Windows
  gather_facts: false
  tasks:
    - name: Show web content variables
      ansible.builtin.debug:
        var: web_content

- name: Play to install IIS
  hosts: webservers
  vars:
    web_service: W3Svc
    web_feature: Web-Server
    web_index: index.html
  max_fail_percentage: 50
  tasks:
    - name: gather disk facts
      community.windows.win_disk_facts:

    - name: Install IIS feature
      ansible.windows.win_feature:
        name: >
          {{ web_feature }}
        state: present

    - name: Start the IIS service
      ansible.windows.win_service:
        name: "{{ web_service }}"
        state: 'started'
        start_mode: auto

    - name: Copy out content
      ansible.windows.win_copy:
        content: |
          {{ web_content }}
          The OS is {{ ansible_facts['os_name'] }}
          Memory on this system {{ ansible_facts.memtotal_mb }}
          Memory on this system {{ ansible_memtotal_mb }}
          First IP address {{ ansible_facts['ip_addresses'][0] }}
          First disk size {{ ansible_facts.disks[0].size }}
          Inventory hostname is {{ inventory_hostname }}
        dest: c:\inetpub\wwwroot\{{ web_index }}

- name: Play to test
  hosts: database
  tasks:
    - name: Test connectivity
      ansible.windows.win_uri:
        url: http://{{ hostvars['win1.example.com']['ansible_facts']['ip_addresses'][0] }}
        return_content: true
      register: uriresult

    - name: put that content in c:\windows\temp
      ansible.windows.win_copy:
        content: '{{ uriresult["content"] }}'
        dest: c:\windows\temp\result.txt
    

- name: Test from the control node
  hosts: localhost
  tasks:
    - name: Test from this linux container
      ansible.builtin.uri:
        url: http://win1.example.com
