---
- name: gather disk facts
  community.windows.win_disk_facts:

- name: Install IIS feature
  ansible.windows.win_feature:
    name: >
      {{ web_feature }}
    state: present

- name: Start the IIS service
  ansible.windows.win_service:
    name: "{{ web_service }}"
    state: 'started'
    start_mode: auto

- name: Copy out content
  ansible.windows.win_copy:
    content: |
      {{ web_content }}
      The OS is {{ ansible_facts['os_name'] }}
      Memory on this system {{ ansible_facts.memtotal_mb }}
      Memory on this system {{ ansible_memtotal_mb }}
      First IP address {{ ansible_facts['ip_addresses'][0] }}
      First disk size {{ ansible_facts.disks[0].size }}
      Inventory hostname is {{ inventory_hostname }}
    dest: c:\inetpub\wwwroot\{{ web_index }}
