---
- name: gather disk facts
  community.windows.win_disk_facts:

- name: Install IIS feature
  ansible.windows.win_feature:
    name: >
      {{ web_feature }}
    state: present

- name: Start the IIS service
  ansible.windows.win_service:
    name: "{{ web_service }}"
    state: 'started'
    start_mode: auto

- name: Copy out content
  ansible.windows.win_template:
    src: content.j2
    dest: c:\inetpub\wwwroot\{{ web_index }}
